#!/bin/bash
# ============================================================================
# emu_agentic GRPO — ToolArtist RL launcher
# ----------------------------------------------------------------------------
# Re-uses ``emu_infer_fast/run.py::EmuAgent`` verbatim through
# verl/workers/rollout/emu_agentic.  No scaffold edits.
#
# Outputs (all under RL/experiments/${EXP}/):
#   experiments/${EXP}/train_<ts>.log    raw stdout (UTF-8 readable)
#   experiments/${EXP}/images/stepNNN/   PNGs generated by EmuAgent that step
#   experiments/${EXP}/traces/stepNNN.jsonl   one row per rollout sample with
#                                        question / prediction / termination /
#                                        cleaned message trace / image paths
#
# Run:
#   cd RL
#   bash UniVR_RL/examples/emu_agentic_grpo.sh
# ============================================================================

set -euo pipefail
set -x

# ── UTF-8 everywhere so 中文 logs / 中文 traces are readable ───────────────
export LC_ALL="${LC_ALL:-C.UTF-8}"
export LANG="${LANG:-C.UTF-8}"
export PYTHONIOENCODING="${PYTHONIOENCODING:-utf-8}"
export PYTHONUTF8=1

# ── Paths ─────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UNIVR_RL_PATH="${UNIVR_RL_PATH:-$(cd "$SCRIPT_DIR/.." && pwd)}"
RL_ROLL_ROOT="${RL_ROLL_ROOT:-$(cd "$UNIVR_RL_PATH/.." && pwd)}"
PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$RL_ROLL_ROOT/.." && pwd)}"
EMU_INFER_FAST_DIR_DEFAULT="$PROJECT_ROOT/Agentic_Image_Gen"
EMU_ROOT_DEFAULT="$PROJECT_ROOT/Emu3.5"
export EMU_INFER_FAST_DIR="${EMU_INFER_FAST_DIR:-${EMU_INFER_FAST_DIR_DEFAULT}}"
export EMU_ROOT="${EMU_ROOT:-${EMU_ROOT_DEFAULT}}"
export PYTHONPATH="${EMU_ROOT}/src:${PYTHONPATH:-}"

# ── Model / tokenizer / VQ (match emu_infer_fast/start.sh) ────────────────
LOCAL_MODEL="${EMU_MODEL_PATH:-$PROJECT_ROOT/checkpoints/emu3p5-sft}"
TOKENIZER_PATH="${EMU_TOKENIZER_PATH:-${EMU_ROOT}/src/tokenizer_emu3_ibq}"
export EMU_TOKENIZER_PATH="${TOKENIZER_PATH}"
export EMU_VQ_PATH="${EMU_VQ_PATH:-$PROJECT_ROOT/checkpoints/Emu3.5-VisionTokenizer}"
export EMU_VQ_TYPE="${EMU_VQ_TYPE:-ibq}"
export EMU_VQ_DEVICE="${EMU_VQ_DEVICE:-cuda:0}"
# rollout TP. Use TP=1 to MATCH the scaffold's verified config (their
# server.gpu*.log shows tensor_parallel_size=1 when generating the good
# images we're trying to reproduce). With 8 ranks → DP=8, each engine owns
# the whole 34B model on one B300 (68 GB weights, 200+ GB free for KV cache).
# This is also strictly faster than TP=2 for our serial-per-prompt rollout:
# 8 engines × 4 traj each (serial) is 2× the concurrency of TP=2 × DP=4.
export EMU_TP_SIZE="${EMU_TP_SIZE:-1}"
export EMU_GPU_MEM_UTIL="${EMU_GPU_MEM_UTIL:-0.6}"
export EMU_SEED="${EMU_SEED:-6666}"

# ── Agent + sampling defaults (mirror emu_infer_fast/start.sh) ────────────
# Agent loop budget — bring-up used (max_rounds=4, force_draw_round=3) which
# left the model only 2 chances to self-emit a real <BoC>caption<EoC> before
# falling back to a fixed force-draw hint (~95% of trajectories ended up on
# force_draw → the judge scored the generic hint as 0 → R_caption gradient is dead).
# Raise to (max_rounds=8, force_draw_round=7): the SFT model can do 4-5 tool
# searches AND still emit its own caption inside the budget. Force_draw stays
# as a safety net at round 7 for runaway trajectories only.
export EMU_MAX_LLM_CALL_PER_RUN="${EMU_MAX_LLM_CALL_PER_RUN:-8}"
export EMU_MAX_NEW_TOKENS="${EMU_MAX_NEW_TOKENS:-8192}"
export EMU_MAX_PROMPT_TOKENS="${EMU_MAX_PROMPT_TOKENS:-30000}"
export EMU_MAX_IMAGE_TOKENS="${EMU_MAX_IMAGE_TOKENS:-8192}"
export EMU_IMAGE_AREA="${EMU_IMAGE_AREA:-1048576}"
export EMU_TEXT_CFG="${EMU_TEXT_CFG:-1.0}"
export EMU_IMAGE_CFG="${EMU_IMAGE_CFG:-3.0}"
export EMU_FORCE_DRAW_ROUND="${EMU_FORCE_DRAW_ROUND:-7}"
export EMU_FORCE_DRAW_HINT="${EMU_FORCE_DRAW_HINT:-Based on all retrieved information and reference images above, render the final image now.}"

# ── Dataset (the user pinned this one) ────────────────────────────────────
# 6172 rows of ``{"idx", "question", "answer"}``. ``EmuAgenticJsonlDataset``
# only reads ``question`` and uses it as both prompt and ground_truth
# (the bring-up reward is purely format-based — no GT image needed).
TRAIN_DATA="${EMU_AGENTIC_TRAIN_DATA:-$PROJECT_ROOT/Data/RL/gen_rl.jsonl}"

# ── Single-node 8x B300 ───────────────────────────────────────────────────
NNODES=1
GPUS_PER_NODE=8

# ── Env hygiene (B300 sm_103a + offline w&b) ──────────────────────────────
export TOKENIZERS_PARALLELISM=false
# ── wandb ────────────────────────────────────────────────────────────────
# Set EMU_DISABLE_WANDB=1 to run offline. Set PROXY_URL if your environment
# needs an outbound proxy.
if [[ "${EMU_DISABLE_WANDB:-0}" == "1" ]]; then
  export WANDB_MODE=offline
  export WANDB_DISABLED=true
else
  unset WANDB_DISABLED
  export WANDB_MODE="${WANDB_MODE:-online}"
  export WANDB_CONSOLE="off"
  export WANDB_BASE_URL="${WANDB_BASE_URL:-https://api.wandb.ai}"
  if [[ -n "${WANDB_ENTITY:-}" ]]; then
    export WANDB_ENTITY
  fi
  if [[ -n "${PROXY_URL:-}" ]]; then
    export http_proxy="${http_proxy:-$PROXY_URL}"
    export https_proxy="${https_proxy:-$PROXY_URL}"
  fi
  export no_proxy="${no_proxy:-localhost,127.0.0.1}"
fi
export TORCHDYNAMO_DISABLE=1
export TORCH_COMPILE_DISABLE=1
export VLLM_DISABLE_COMPILE_CACHE=1
export TORCHINDUCTOR_FORCE_DISABLE_CACHES=1
export EMU_ENFORCE_EAGER=1
# Use CUDA-12.9 ptxas (knows sm_103a). The bundled 12.8 ptxas does not.
export TRITON_PTXAS_PATH="${TRITON_PTXAS_PATH:-/opt/conda/envs/agent/lib/python3.12/site-packages/nvidia/cuda_nvcc/bin/ptxas}"
unset TRITON_OVERRIDE_ARCH || true
export VLLM_LOGGING_LEVEL=WARN
export VLLM_ALLREDUCE_USE_SYMM_MEM=0
export NCCL_DEBUG=WARN
export TORCH_NCCL_AVOID_RECORD_STREAMS=1
export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:False"
export CUDA_DEVICE_MAX_CONNECTIONS=1
export VLLM_USE_V1=1

# Activate conda env if not already in one.
if [[ -z "${CONDA_DEFAULT_ENV:-}" ]]; then
  source /opt/conda/etc/profile.d/conda.sh
  conda activate agent
fi

# ── Experiment naming + output paths ──────────────────────────────────────
PROJECT_NAME="${PROJECT_NAME:-Emu3_Agentic_RL_Roll}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-emu_agentic_grpo}"
EXP_DIR="${RL_ROLL_ROOT}/experiments/${EXPERIMENT_NAME}"
IMAGE_SAVE_DIR="${EXP_DIR}/images"
TRACE_DIR="${EXP_DIR}/traces"
LOG_FILE="${EXP_DIR}/train_$(date +%Y%m%d_%H%M%S).log"
mkdir -p "${IMAGE_SAVE_DIR}" "${TRACE_DIR}"
export EMU_IMAGE_SAVE_DIR="${IMAGE_SAVE_DIR}"
export EMU_TRACE_DIR="${TRACE_DIR}"

cat <<EOF
[launch] project           : ${PROJECT_NAME}
[launch] experiment        : ${EXPERIMENT_NAME}
[launch] model             : ${LOCAL_MODEL}
[launch] tokenizer         : ${TOKENIZER_PATH}
[launch] train data        : ${TRAIN_DATA}
[launch] EMU_INFER_FAST_DIR: ${EMU_INFER_FAST_DIR}
[launch] EMU_ROOT          : ${EMU_ROOT}
[launch] EMU_VQ_PATH       : ${EMU_VQ_PATH}
[launch] image save dir    : ${IMAGE_SAVE_DIR}
[launch] trace dir         : ${TRACE_DIR}
[launch] log file          : ${LOG_FILE}
[launch] gpus              : ${NNODES}x${GPUS_PER_NODE}
EOF

cd "${UNIVR_RL_PATH}"

python3 -m verl.trainer.main \
    config=examples/config_emu_agentic.yaml \
    data.train_files="${TRAIN_DATA}" \
    worker.actor.model.model_path="${LOCAL_MODEL}" \
    worker.actor.model.tokenizer_path="${TOKENIZER_PATH}" \
    worker.actor.model.trust_remote_code=true \
    worker.actor.fsdp.torch_dtype=bf16 \
    worker.actor.padding_free=false \
    worker.actor.use_torch_compile=false \
    worker.rollout.name=emu_agentic \
    worker.rollout.tensor_parallel_size=${EMU_TP_SIZE} \
    worker.rollout.gpu_memory_utilization=0.6 \
    worker.rollout.enable_image_decode_for_reward=false \
    worker.actor.model.lora.rank=0 \
    worker.actor.model.lora.alpha=0 \
    trainer.experiment_name="${EXPERIMENT_NAME}" \
    trainer.project_name="${PROJECT_NAME}" \
    trainer.n_gpus_per_node=${GPUS_PER_NODE} \
    trainer.nnodes=${NNODES} \
    trainer.max_steps=200 \
    trainer.save_freq=-1 \
    trainer.save_checkpoint_path="${EXP_DIR}/checkpoints" \
    data.rollout_batch_size=16 \
    worker.actor.global_batch_size=16 \
    worker.rollout.n=8 \
    2>&1 | tee -a "${LOG_FILE}"
